theme: jekyll-theme-slate
title: Samples and Blog - Yarri Bryn
description: Collection of content including small coding projects, machine learning, and blogs about data science.
github_username: yarrib
