theme: jekyll-theme-slate
title: Projects and Thoughts from @yarrib
description: This is where I'll put content and blog posts related to personal projects and education I'm pursuing
github_username: yarrib
