project:
  type: website

website:
  title: "Yarri Bryn"
  navbar:
    search: true
    right:
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: index.qmd
      - text: "TIL"
        file: til.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css
