project:
  type: website

website:
  title: "yarrib.github.io"
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css



