project:
  type: website

website:
  title: "Yarri Bryn"
  description: "Personal Blog for Yarri Bryn"
  site-url: "https://yarrib.github.io/"
  navbar:
    search: true
    right:
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "How To's"
        file: howto.qmd
      - icon: github
        href: https://github.com/yarrib
      - icon: linkedin
        href: https://www.linkedin.com/in/yarribryn
      - text: kaggle
        href: https://www.kaggle.com/yarribryn
  google-analytics:
    tracking-id: "G-KHJ8SVY1DV"
    version: 4
    #anonymize-ip: true
  cookie-consent: true

  # comments: 
  #   utterances:
  #     repo: https://github.com/yarrib/yarrib.github.io


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
