project:
  type: website

website:
  title: "Yarri Bryn"
  description: "Personal Blog for Yarri Bryn"
  site-url: "https://yarrib.github.io/"
  navbar:
    search: true
    right:
      - text: "About"
        file: about.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "How To's"
        file: howto.qmd
      - icon: github
        href: https://github.com/yarrib
      - icon: linkedin
        href: https://www.linkedin.com/in/yarribryn
      - text: kaggle
        href: https://kaggle.com

  comments: 
    utterances:
      repo: https://github.com/yarrib/yarrib.github.io


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
